import Head from "next/head";

type Props = {
  title?: string;
  children?: JSX.Element;
};

const HeadComponent = ({ children, title }: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={"Generated by " + title} />
      <link rel="icon" href="../../../../../public/favicon.ico" />
    </Head>
  );
};

export default HeadComponent;
